spring.application.name=teams_app

# datasource connection properties
spring.datasource.url=jdbc:postgresql://localhost:5432/teams_app
spring.datasource.name=teams_app
spring.datasource.username=postgres
spring.datasource.password=postgres1

server.error.include-stacktrace=never
server.port=9000